fisher:
  plugins:
    - "catppuccin/fish"
    - "danhper/fish-ssh-agent"
    - "demartini/upmm.fish"
    - "jorgebucaran/autopair.fish"
    - "gazorby/fish-abbreviation-tips"
    - "nickeb96/puffer-fish"
    - "patrickf1/fzf.fish"
