packages:
  darwin:
    brews:
      - "atuin"
      - "autoconf"
      - "bash"
      - "bat"
      - "btop"
      - "coreutils"
      - "curl"
      - "diff-so-fancy"
      - "eza"
      - "fd"
      - "ffmpeg"
      - "fnm"
      - "fzf"
      - "gdu"
      - "gh"
      - "git"
      - "gitui"
      - "go"
      - "httpie"
      - "imagemagick"
      - "jenv"
      - "lazygit"
      - "mailpit"
      - "mas"
      - "moreutils"
      - "node"
      - "openjdk"
      - "openssl@3"
      - "pkgconf"
      - "pnpm"
      - "poetry"
      - "pre-commit"
      - "pyenv"
      - "ripgrep"
      - "ruby"
      - "ruff"
      - "shfmt"
      - "starship"
      - "tealdeer"
      - "the_silver_searcher"
      - "thefuck"
      - "tokei"
      - "tree"
      - "vhs"
      - "walk"
      - "wget"
      - "yt-dlp"
      - "zoxide"
    casks:
      - "android-studio"
      - "anydesk"
      - "asana"
      - "beekeeper-studio"
      - "canva"
      - "direqual"
      - "discord"
      - "docker"
      - "dropbox"
      - "enpass"
      - "figma"
      - "firefox"
      - "font-cascadia-code"
      - "font-caskaydia-cove-nerd-font"
      - "font-jetbrains-mono-nerd-font"
      - "font-jetbrains-mono"
      - "font-recursive-code"
      - "font-recursive-mono-nerd-font"
      - "git-credential-manager"
      - "github"
      - "google-chrome"
      - "gpg-suite"
      - "hammerspoon"
      - "handbrake"
      - "herd"
      - "httpie"
      - "iterm2"
      - "keybase"
      - "macfuse"
      - "notion"
      - "obsidian"
      - "openinterminal"
      - "opera"
      - "plex"
      - "postgres-unofficial"
      - "postman"
      - "rapidapi"
      - "raycast"
      - "skype"
      - "slack"
      - "spotify"
      - "syntax-highlight"
      - "teamviewer"
      - "telegram"
      - "tg-pro"
      - "the-unarchiver"
      - "transmission"
      - "transnomino"
      - "virtualbox"
      - "visual-studio-code"
      - "vlc"
      - "warp"
      - "whatsapp"
      - "wpsoffice"
    mas:
      - name: "CapCut"
        id: "1500855883"
      - name: "Color Picker"
        id: "1545870783"
      - name: "DirEqual"
        id: "1435575700"
      - name: "Shazam"
        id: "897118787"
      - name: "Unsplash Wallpapers"
        id: "1284863847"
    taps:
      - "buo/cask-upgrade"
